use crate::codex::{CodexEntry, CodexCategory, UnlockTrigger};

pub fn all_entries() -> Vec<CodexEntry> {
    vec![
        // --- Species (8) ---
        CodexEntry {
            id: "species_thermophile".into(),
            category: CodexCategory::Species,
            name: "Thermophile".into(),
            unlock_trigger: UnlockTrigger::SpeciesAppeared,
            requirements_text: "Seed initial life on a barren world.".into(),
            facts_text: "Heat-loving microorganisms that thrive near volcanic vents. They metabolize sulfur compounds and can survive temperatures exceeding 80°C.".into(),
            flavor_text: "The first spark — life clinging to warmth in the dark.".into(),
            related_entry_ids: vec!["bodyplan_chemosynthetic".into()],
            icon_asset_id: "microbe".into(),
        },
        CodexEntry {
            id: "species_planktonic_algae".into(),
            category: CodexCategory::Species,
            name: "Planktonic Algae".into(),
            unlock_trigger: UnlockTrigger::SpeciesAppeared,
            requirements_text: "Begin Level 2 with a marine ecosystem.".into(),
            facts_text: "Free-floating photosynthetic organisms forming the base of marine food webs. They convert sunlight and dissolved nutrients into biomass.".into(),
            flavor_text: "Green clouds drifting through alien seas — the ocean breathes.".into(),
            related_entry_ids: vec!["biome_shallow_reef".into(), "species_grazer".into()],
            icon_asset_id: "leaf".into(),
        },
        CodexEntry {
            id: "species_grazer".into(),
            category: CodexCategory::Species,
            name: "Grazer".into(),
            unlock_trigger: UnlockTrigger::SpeciesAppeared,
            requirements_text: "Begin Level 2 with a marine ecosystem.".into(),
            facts_text: "Filter-feeding organisms that consume producers. Their population oscillates with prey availability in classic predator-prey cycles.".into(),
            flavor_text: "Mouths without eyes, straining life from the current.".into(),
            related_entry_ids: vec!["species_planktonic_algae".into(), "species_apex_filter".into()],
            icon_asset_id: "fish".into(),
        },
        CodexEntry {
            id: "species_apex_filter".into(),
            category: CodexCategory::Species,
            name: "Apex Filter".into(),
            unlock_trigger: UnlockTrigger::SpeciesAppeared,
            requirements_text: "Begin Level 2 with a marine ecosystem.".into(),
            facts_text: "Top predators of the early marine ecosystem. They regulate consumer populations, preventing overgrazing of producers.".into(),
            flavor_text: "Patient hunters in the deep — the ocean's balance keepers.".into(),
            related_entry_ids: vec!["species_grazer".into(), "event_trophic_cascade".into()],
            icon_asset_id: "bolt".into(),
        },
        CodexEntry {
            id: "species_first_mutant".into(),
            category: CodexCategory::Species,
            name: "First Mutant".into(),
            unlock_trigger: UnlockTrigger::SpeciationEvent,
            requirements_text: "Observe the first speciation event.".into(),
            facts_text: "When environmental pressure meets genetic drift, a lineage splits. The child species carries mutated traits better suited to local conditions.".into(),
            flavor_text: "Something new. Something that was not planned.".into(),
            related_entry_ids: vec!["event_first_speciation".into()],
            icon_asset_id: "sparkles".into(),
        },
        CodexEntry {
            id: "species_deep_dweller".into(),
            category: CodexCategory::Species,
            name: "Deep Dweller".into(),
            unlock_trigger: UnlockTrigger::TraitStabilized { trait_name: "temp_optimal_below_zero".into(), min_duration: 100_000 },
            requirements_text: "A species with sub-zero optimal temperature survives 100K years.".into(),
            facts_text: "Organisms adapted to extreme cold, thriving in conditions that would freeze most life. Their biochemistry uses antifreeze proteins.".into(),
            flavor_text: "Where others see death, they find home.".into(),
            related_entry_ids: vec!["bodyplan_chemosynthetic".into(), "biome_frozen_waste".into()],
            icon_asset_id: "snowflake".into(),
        },
        CodexEntry {
            id: "species_radiation_resistant".into(),
            category: CodexCategory::Species,
            name: "Radiation Resistant".into(),
            unlock_trigger: UnlockTrigger::TraitStabilized { trait_name: "toxin_resistance_high".into(), min_duration: 100_000 },
            requirements_text: "A species with toxin_resistance > 0.6 survives 100K years.".into(),
            facts_text: "These organisms developed robust DNA repair mechanisms and radiation-absorbing pigments, allowing survival in high-radiation environments.".into(),
            flavor_text: "Bathed in starfire, yet unbroken.".into(),
            related_entry_ids: vec!["bodyplan_toxin_immune".into()],
            icon_asset_id: "bolt.shield".into(),
        },
        CodexEntry {
            id: "species_cold_adapted".into(),
            category: CodexCategory::Species,
            name: "Cold Adapted".into(),
            unlock_trigger: UnlockTrigger::TraitStabilized { trait_name: "temp_optimal_very_cold".into(), min_duration: 200_000 },
            requirements_text: "A species with temp_optimal < -20°C survives 200K years.".into(),
            facts_text: "Psychrophilic organisms that have replaced water in their cells with cryoprotectant compounds. They reproduce slowly but persistently.".into(),
            flavor_text: "Ice is not the end. It is a beginning no one expected.".into(),
            related_entry_ids: vec!["species_deep_dweller".into(), "failure_frozen_death".into()],
            icon_asset_id: "thermometer.snowflake".into(),
        },

        // --- Body Plans (4) ---
        CodexEntry {
            id: "bodyplan_chemosynthetic".into(),
            category: CodexCategory::BodyPlan,
            name: "Chemosynthetic".into(),
            unlock_trigger: UnlockTrigger::TraitStabilized { trait_name: "temp_optimal_below_neg10".into(), min_duration: 500_000 },
            requirements_text: "A species with temp_optimal < -10°C stabilized for 500K years.".into(),
            facts_text: "Organisms that derive energy from chemical reactions rather than sunlight. They thrive near hydrothermal vents and in subsurface environments.".into(),
            flavor_text: "Life that feeds on the planet itself.".into(),
            related_entry_ids: vec!["biome_hydrothermal_vent".into(), "species_deep_dweller".into()],
            icon_asset_id: "flame".into(),
        },
        CodexEntry {
            id: "bodyplan_thermophilic".into(),
            category: CodexCategory::BodyPlan,
            name: "Thermophilic".into(),
            unlock_trigger: UnlockTrigger::TraitStabilized { trait_name: "temp_optimal_above_40".into(), min_duration: 500_000 },
            requirements_text: "A species with temp_optimal > 40°C stabilized for 500K years.".into(),
            facts_text: "Heat-loving organisms with proteins that remain stable at extreme temperatures. Their enzymes function optimally above the boiling point of many solvents.".into(),
            flavor_text: "Forged in heat. Tempered by time.".into(),
            related_entry_ids: vec!["species_thermophile".into(), "system_greenhouse".into()],
            icon_asset_id: "thermometer.sun".into(),
        },
        CodexEntry {
            id: "bodyplan_pressure_adapted".into(),
            category: CodexCategory::BodyPlan,
            name: "Pressure Adapted".into(),
            unlock_trigger: UnlockTrigger::TraitStabilized { trait_name: "o2_need_very_low".into(), min_duration: 500_000 },
            requirements_text: "A species with o2_need < 0.02 stabilized for 500K years.".into(),
            facts_text: "Anaerobic organisms that evolved to thrive without oxygen. They use alternative electron acceptors for respiration.".into(),
            flavor_text: "They remember a time before breath.".into(),
            related_entry_ids: vec!["system_oxygenated".into()],
            icon_asset_id: "wind".into(),
        },
        CodexEntry {
            id: "bodyplan_toxin_immune".into(),
            category: CodexCategory::BodyPlan,
            name: "Toxin Immune".into(),
            unlock_trigger: UnlockTrigger::TraitStabilized { trait_name: "toxin_resistance_very_high".into(), min_duration: 500_000 },
            requirements_text: "A species with toxin_resistance > 0.8 stabilized for 500K years.".into(),
            facts_text: "Organisms with extraordinary detoxification pathways. They metabolize compounds that are lethal to most life forms.".into(),
            flavor_text: "Poison is just another flavor.".into(),
            related_entry_ids: vec!["species_radiation_resistant".into(), "biome_toxic_basin".into()],
            icon_asset_id: "shield".into(),
        },

        // --- Biomes (5) ---
        CodexEntry {
            id: "biome_hydrothermal_vent".into(),
            category: CodexCategory::Biome,
            name: "Hydrothermal Vent".into(),
            unlock_trigger: UnlockTrigger::BiomeCondition { criteria: "ocean_hot_nutrient".into(), min_tiles: 3 },
            requirements_text: "3+ ocean tiles with temperature > 40°C and nutrients > 0.5.".into(),
            facts_text: "Submarine volcanic vents create oases of chemical energy. Superheated water carries dissolved minerals that sustain chemosynthetic ecosystems.".into(),
            flavor_text: "Where the planet bleeds, life drinks deep.".into(),
            related_entry_ids: vec!["bodyplan_chemosynthetic".into()],
            icon_asset_id: "flame.fill".into(),
        },
        CodexEntry {
            id: "biome_frozen_waste".into(),
            category: CodexCategory::Biome,
            name: "Frozen Waste".into(),
            unlock_trigger: UnlockTrigger::BiomeCondition { criteria: "land_frozen".into(), min_tiles: 10 },
            requirements_text: "10+ land tiles with temperature < -30°C.".into(),
            facts_text: "Vast frozen expanses where temperatures plunge far below freezing. Only the hardiest extremophiles survive in thin liquid water films between ice crystals.".into(),
            flavor_text: "A silence so deep it has weight.".into(),
            related_entry_ids: vec!["species_cold_adapted".into(), "failure_frozen_death".into()],
            icon_asset_id: "snow".into(),
        },
        CodexEntry {
            id: "biome_shallow_reef".into(),
            category: CodexCategory::Biome,
            name: "Shallow Reef".into(),
            unlock_trigger: UnlockTrigger::BiomeCondition { criteria: "ocean_warm_populated".into(), min_tiles: 5 },
            requirements_text: "5+ ocean tiles with temp 10-30°C and population > 100.".into(),
            facts_text: "Warm, nutrient-rich shallows teeming with life. The highest biodiversity density in any marine environment, driven by stable conditions and abundant energy.".into(),
            flavor_text: "The sea remembers how to be alive.".into(),
            related_entry_ids: vec!["species_planktonic_algae".into(), "system_ocean_world".into()],
            icon_asset_id: "water.waves".into(),
        },
        CodexEntry {
            id: "biome_toxic_basin".into(),
            category: CodexCategory::Biome,
            name: "Toxic Basin".into(),
            unlock_trigger: UnlockTrigger::BiomeCondition { criteria: "toxic_inhabited".into(), min_tiles: 3 },
            requirements_text: "3+ tiles with toxicity > 0.5 and any population present.".into(),
            facts_text: "Acidic pools and toxic flats where conventional biology fails. Extremophiles here have evolved radical biochemical adaptations.".into(),
            flavor_text: "Life finds a way. Even here.".into(),
            related_entry_ids: vec!["bodyplan_toxin_immune".into()],
            icon_asset_id: "exclamationmark.triangle".into(),
        },
        CodexEntry {
            id: "biome_nutrient_desert".into(),
            category: CodexCategory::Biome,
            name: "Nutrient Desert".into(),
            unlock_trigger: UnlockTrigger::BiomeCondition { criteria: "land_barren".into(), min_tiles: 20 },
            requirements_text: "20+ land tiles with nutrients < 0.05.".into(),
            facts_text: "Sterile landscapes stripped of bioavailable minerals. Without volcanic activity or biological recycling, these regions remain lifeless.".into(),
            flavor_text: "The planet's bones, picked clean.".into(),
            related_entry_ids: vec![],
            icon_asset_id: "sun.dust".into(),
        },

        // --- Planetary Systems (5) ---
        CodexEntry {
            id: "system_greenhouse".into(),
            category: CodexCategory::PlanetarySystem,
            name: "Greenhouse World".into(),
            unlock_trigger: UnlockTrigger::ParamThreshold { param: "co2".into(), min_value: 0.2 },
            requirements_text: "Atmospheric CO2 exceeds 0.2.".into(),
            facts_text: "Runaway greenhouse conditions trap heat in the atmosphere. Surface temperatures rise dramatically, melting ice and altering weather patterns.".into(),
            flavor_text: "The sky becomes a blanket. Then a prison.".into(),
            related_entry_ids: vec!["failure_runaway_greenhouse".into(), "bodyplan_thermophilic".into()],
            icon_asset_id: "sun.max".into(),
        },
        CodexEntry {
            id: "system_oxygenated".into(),
            category: CodexCategory::PlanetarySystem,
            name: "Oxygenated Atmosphere".into(),
            unlock_trigger: UnlockTrigger::ParamThreshold { param: "o2".into(), min_value: 0.15 },
            requirements_text: "Atmospheric O2 exceeds 0.15.".into(),
            facts_text: "A critical threshold in planetary evolution. Sufficient oxygen enables aerobic metabolism — dramatically more efficient energy extraction from food.".into(),
            flavor_text: "The world learns to breathe. Everything changes.".into(),
            related_entry_ids: vec!["bodyplan_pressure_adapted".into()],
            icon_asset_id: "wind".into(),
        },
        CodexEntry {
            id: "system_magnetosphere".into(),
            category: CodexCategory::PlanetarySystem,
            name: "Strong Magnetosphere".into(),
            unlock_trigger: UnlockTrigger::ParamThreshold { param: "magnetic_field".into(), min_value: 0.7 },
            requirements_text: "Magnetic field strength exceeds 0.7.".into(),
            facts_text: "A powerful magnetic field deflects charged particles from the star, protecting the atmosphere from being stripped away and shielding surface life from radiation.".into(),
            flavor_text: "An invisible shield. The planet's silent guardian.".into(),
            related_entry_ids: vec!["species_radiation_resistant".into()],
            icon_asset_id: "shield.lefthalf.filled".into(),
        },
        CodexEntry {
            id: "system_ocean_world".into(),
            category: CodexCategory::PlanetarySystem,
            name: "Ocean World".into(),
            unlock_trigger: UnlockTrigger::ParamThreshold { param: "ocean_coverage".into(), min_value: 0.7 },
            requirements_text: "Ocean coverage exceeds 0.7.".into(),
            facts_text: "A planet dominated by liquid water. Ocean worlds moderate temperature extremes and provide vast habitable volume, but limited mineral cycling slows evolution.".into(),
            flavor_text: "A single, unbroken mirror reflecting the sky.".into(),
            related_entry_ids: vec!["biome_shallow_reef".into(), "system_tidal_engine".into()],
            icon_asset_id: "globe.americas".into(),
        },
        CodexEntry {
            id: "system_tidal_engine".into(),
            category: CodexCategory::PlanetarySystem,
            name: "Tidal Engine".into(),
            unlock_trigger: UnlockTrigger::ParamThreshold { param: "current_strength".into(), min_value: 0.7 },
            requirements_text: "Ocean current strength exceeds 0.7.".into(),
            facts_text: "Strong tidal forces drive powerful ocean currents that distribute heat and nutrients globally. Upwelling zones become hotspots of biological productivity.".into(),
            flavor_text: "The ocean stirs. Nutrients rise. Life follows.".into(),
            related_entry_ids: vec!["system_ocean_world".into()],
            icon_asset_id: "water.waves".into(),
        },

        // --- Evolutionary Events (5) ---
        CodexEntry {
            id: "event_first_speciation".into(),
            category: CodexCategory::EvolutionaryEvent,
            name: "First Speciation".into(),
            unlock_trigger: UnlockTrigger::SpeciationEvent,
            requirements_text: "Observe the first speciation event.".into(),
            facts_text: "When a population becomes isolated or faces divergent selective pressures, accumulated mutations can split a single lineage into two distinct species.".into(),
            flavor_text: "One becomes two. The tree of life branches.".into(),
            related_entry_ids: vec!["species_first_mutant".into()],
            icon_asset_id: "arrow.triangle.branch".into(),
        },
        CodexEntry {
            id: "event_adaptive_radiation".into(),
            category: CodexCategory::EvolutionaryEvent,
            name: "Adaptive Radiation".into(),
            unlock_trigger: UnlockTrigger::BiodiversityThreshold { min_species: 5 },
            requirements_text: "5 or more species alive simultaneously.".into(),
            facts_text: "A burst of speciation as organisms rapidly diversify to fill available ecological niches. Often triggered by the opening of new habitats or the extinction of competitors.".into(),
            flavor_text: "The world offers a thousand niches. Life fills them all.".into(),
            related_entry_ids: vec!["event_first_speciation".into()],
            icon_asset_id: "chart.line.uptrend.xyaxis".into(),
        },
        CodexEntry {
            id: "event_trophic_cascade".into(),
            category: CodexCategory::EvolutionaryEvent,
            name: "Trophic Cascade".into(),
            unlock_trigger: UnlockTrigger::TrophicCascade,
            requirements_text: "A predator or consumer crash causes a cascading population shift.".into(),
            facts_text: "When a key species in the food web collapses, the effects ripple through all trophic levels. Prey populations explode, then crash as resources deplete.".into(),
            flavor_text: "One thread pulled. The whole web shudders.".into(),
            related_entry_ids: vec!["species_apex_filter".into(), "failure_trophic_collapse".into()],
            icon_asset_id: "arrow.down.right.and.arrow.up.left".into(),
        },
        CodexEntry {
            id: "event_population_explosion".into(),
            category: CodexCategory::EvolutionaryEvent,
            name: "Population Explosion".into(),
            unlock_trigger: UnlockTrigger::PopulationExplosion { min_population: 50_000.0 },
            requirements_text: "Any species exceeds 50,000 global population.".into(),
            facts_text: "Exponential growth unchecked by predation or resource limits. Population explosions are temporary — carrying capacity always reasserts itself.".into(),
            flavor_text: "Numbers without limit. Until the limit arrives.".into(),
            related_entry_ids: vec!["event_trophic_cascade".into()],
            icon_asset_id: "arrow.up.right".into(),
        },
        CodexEntry {
            id: "event_stable_ecosystem".into(),
            category: CodexCategory::EvolutionaryEvent,
            name: "Stable Ecosystem".into(),
            unlock_trigger: UnlockTrigger::StableEcosystem { min_duration: 1_000_000 },
            requirements_text: "All 3 trophic levels sustained for 1M years.".into(),
            facts_text: "A mature ecosystem where producers, consumers, and predators coexist in dynamic equilibrium. Population oscillations dampen over time as the web stabilizes.".into(),
            flavor_text: "Not perfection. Balance. And that is enough.".into(),
            related_entry_ids: vec!["species_grazer".into(), "species_apex_filter".into()],
            icon_asset_id: "checkmark.seal".into(),
        },

        // --- Failure Modes (4) ---
        CodexEntry {
            id: "failure_total_extinction".into(),
            category: CodexCategory::FailureMode,
            name: "Total Extinction".into(),
            unlock_trigger: UnlockTrigger::TotalExtinction,
            requirements_text: "All life goes extinct.".into(),
            facts_text: "Complete biosphere collapse. When conditions exceed the tolerance of every living species simultaneously, the planet returns to sterility.".into(),
            flavor_text: "Silence. The loudest sound a world can make.".into(),
            related_entry_ids: vec!["failure_runaway_greenhouse".into(), "failure_frozen_death".into()],
            icon_asset_id: "xmark.circle".into(),
        },
        CodexEntry {
            id: "failure_runaway_greenhouse".into(),
            category: CodexCategory::FailureMode,
            name: "Runaway Greenhouse".into(),
            unlock_trigger: UnlockTrigger::RunawayGreenhouse,
            requirements_text: "Average surface temperature exceeds 60°C.".into(),
            facts_text: "A positive feedback loop: higher temperatures release more greenhouse gases, which trap more heat. Venus suffered this fate — surface temperatures hot enough to melt lead.".into(),
            flavor_text: "The sky turns to copper. The oceans boil away.".into(),
            related_entry_ids: vec!["system_greenhouse".into(), "failure_total_extinction".into()],
            icon_asset_id: "thermometer.sun.fill".into(),
        },
        CodexEntry {
            id: "failure_frozen_death".into(),
            category: CodexCategory::FailureMode,
            name: "Frozen Death".into(),
            unlock_trigger: UnlockTrigger::FrozenDeath,
            requirements_text: "Ice fraction exceeds 0.9.".into(),
            facts_text: "Snowball planet. Ice reflects sunlight, cooling the surface further, creating more ice. Without volcanic CO2 to break the cycle, the planet freezes solid.".into(),
            flavor_text: "White. Everywhere. Forever.".into(),
            related_entry_ids: vec!["biome_frozen_waste".into(), "failure_total_extinction".into()],
            icon_asset_id: "snowflake".into(),
        },
        CodexEntry {
            id: "failure_trophic_collapse".into(),
            category: CodexCategory::FailureMode,
            name: "Trophic Collapse".into(),
            unlock_trigger: UnlockTrigger::TrophicCollapse,
            requirements_text: "An entire trophic level loses all species.".into(),
            facts_text: "When all species of one trophic level go extinct, the food web breaks. Without producers, consumers starve. Without predators, consumers overgraze.".into(),
            flavor_text: "The chain snaps. Everything above it falls.".into(),
            related_entry_ids: vec!["event_trophic_cascade".into(), "failure_total_extinction".into()],
            icon_asset_id: "link".into(),
        },

        // --- Rare Phenomena (2) — Locked Previews ---
        CodexEntry {
            id: "rare_silicon_life".into(),
            category: CodexCategory::RarePhenomenon,
            name: "Silicon Life".into(),
            unlock_trigger: UnlockTrigger::Placeholder,
            requirements_text: "Unlocked in advanced levels.".into(),
            facts_text: "Theoretical organisms using silicon-based biochemistry instead of carbon. Possible on worlds with abundant silicates and extreme temperatures.".into(),
            flavor_text: "Crystal minds dreaming in geological time.".into(),
            related_entry_ids: vec![],
            icon_asset_id: "diamond".into(),
        },
        CodexEntry {
            id: "rare_living_crust".into(),
            category: CodexCategory::RarePhenomenon,
            name: "Living Crust".into(),
            unlock_trigger: UnlockTrigger::Placeholder,
            requirements_text: "Unlocked in advanced levels.".into(),
            facts_text: "A planetary-scale organism integrated into the geological substrate. The boundary between life and geology dissolves entirely.".into(),
            flavor_text: "The planet breathes. Not metaphorically.".into(),
            related_entry_ids: vec![],
            icon_asset_id: "globe.europe.africa".into(),
        },

        // --- Historic Worlds (2) — Locked Previews ---
        CodexEntry {
            id: "historic_earth_analog".into(),
            category: CodexCategory::HistoricWorld,
            name: "Earth Analog".into(),
            unlock_trigger: UnlockTrigger::Placeholder,
            requirements_text: "Unlocked in advanced levels.".into(),
            facts_text: "A world that closely mirrors Earth's evolutionary trajectory. Liquid water, plate tectonics, and a protective magnetosphere create ideal conditions for complex life.".into(),
            flavor_text: "Familiar, yet impossibly distant.".into(),
            related_entry_ids: vec![],
            icon_asset_id: "globe.americas".into(),
        },
        CodexEntry {
            id: "historic_titan_echo".into(),
            category: CodexCategory::HistoricWorld,
            name: "Titan Echo".into(),
            unlock_trigger: UnlockTrigger::Placeholder,
            requirements_text: "Unlocked in advanced levels.".into(),
            facts_text: "A frozen moon with liquid hydrocarbon lakes. If life exists here, it uses an entirely alien biochemistry — methane as solvent instead of water.".into(),
            flavor_text: "Rain falls upward. Lakes burn cold. Life persists.".into(),
            related_entry_ids: vec![],
            icon_asset_id: "moon".into(),
        },
    ]
}
